import dspy
from dspy import InputField, OutputField, Predict

class Summarizersignature(dspy.Signature):
    """ Summarize the conversation history between the user and the agent by generating a concise summary that captures meaningful context for future interactions.
    The summary should not exceed three sentences."""
    old_history: str = InputField(desc="the previous conversation history between the user and the agent")
    question: str = InputField(desc="the user question")
    result: str = InputField(desc="the latest result generated by the agent to be summarized into the history")

    new_history: str = OutputField(desc="New updated summary of the conversation history")

class SummarizerModule(dspy.Module):
    def __init__(self):
        super().__init__()
        self.summarize = Predict(Summarizersignature)

    def forward(self, old_history: str, question: str, result: str):
        result = self.summarize(
            old_history=old_history,
            question=question,
            result=result,
        )
        return result


summarizer= SummarizerModule()